/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#281400",
        "on-primary-fixed-variant": "#39475f",
        "inverse-surface": "#e1e3e4",
        "on-secondary-fixed": "#121c28",
        "on-primary-container": "#74829d",
        "secondary-fixed-dim": "#bdc7d8",
        "on-secondary-container": "#afb9c9",
        "on-secondary": "#27313e",
        "surface-dim": "#111415",
        "on-secondary-fixed-variant": "#3e4755",
        "surface-container-low": "#191c1d",
        "on-surface-variant": "#c5c6cd",
        "surface-tint": "#b9c7e4",
        "surface-container-highest": "#323536",
        "on-tertiary-fixed-variant": "#5d4124",
        "surface": "#111415",
        "outline": "#8f9097",
        "surface-bright": "#373a3b",
        "on-error-container": "#ffdad6",
        "primary": "#b9c7e4",
        "surface-container-lowest": "#0c0f10",
        "secondary": "#bdc7d8",
        "tertiary-fixed-dim": "#e7bf99",
        "inverse-primary": "#515f78",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "on-background": "#e1e3e4",
        "on-primary-fixed": "#0d1c32",
        "surface-container": "#1d2021",
        "secondary-fixed": "#d9e3f4",
        "background": "#111415",
        "on-tertiary-fixed": "#2b1701",
        "on-primary": "#233148",
        "error-container": "#93000a",
        "primary-fixed-dim": "#b9c7e4",
        "outline-variant": "#44474d",
        "tertiary-fixed": "#ffdcbd",
        "surface-container-high": "#282a2b",
        "inverse-on-surface": "#2e3132",
        "primary-fixed": "#d6e3ff",
        "primary-container": "#0a192f",
        "secondary-container": "#404a57",
        "on-tertiary": "#432b10",
        "on-surface": "#e1e3e4",
        "surface-variant": "#323536",
        "on-tertiary-container": "#9d7b5a",
        "tertiary": "#e7bf99"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "sm": "12px",
        "base": "8px",
        "lg": "48px",
        "gutter": "24px",
        "xl": "80px",
        "xs": "4px"
      },
      fontFamily: {
        "headline-xl": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
